config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # as 7 rotas do crud são a mesma coisa que resources :restaurants
  get '/restaurants', to: 'restaurants#index'
  post '/restaurants', to: 'restaurants#create'
  get '/restaurants/new', to: 'restaurants#new', as: :new_restaurant
  get '/restaurants/:id', to: 'restaurants#show', as: :restaurant
  patch '/restaurants/:id', to: 'restaurants#update'
  delete '/restaurants/:id', to: 'restaurants#destroy'
  get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    # lista todos os restaurantes
    @restaurants = Restaurant.all
  end

  def show
    # mostra os detalhes de um restaurante
  end

  def new
    # mostra o formulário para criar um restaurante novo
    # precisamos de uma instância de Restaurant para criar o formulário
    @restaurant = Restaurant.new
  end

  def create
    # recebe um formulário para criar um restaurante novo
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    # não precisamos mostrar uma página de create, redirecionamos para a show do
    # restaurante criado
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    # mostra o formulário para editar um restaurante
  end

  def update
    # recebe um formulário para editar um restaurante
    @restaurant.update(restaurant_params)
    # não precisamos mostrar uma página de update, redirecionamos para a show do
    # restaurante editado
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    # apaga um restaurante
    @restaurant.destroy
    # não precisamos mostrar uma página de destroy, redirecionamos para o index
    # de restaurantes
    redirect_to restaurants_path, status: :see_other
  end

  private

  def set_restaurant
    # encontra um restaurante pelo id que está na URL
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    # autoriza expressamente os atributos de restaurante (strong params)
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lww1780RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%# usa a variável local restaurant (que é uma instância de Restaurant) para gerar o formulário %>
<%= form_with model: restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>
<%# Renderiza a partial _form.html.erb enviando o @restaurant como variável local %>
<%= render 'form', restaurant: @restaurant %>
<hr>
<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<%= link_to 'Add a new restaurant', new_restaurant_path %>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>
<%# Renderiza a partial _form.html.erb enviando o @restaurant como variável local %>
<%= render 'form', restaurant: @restaurant %>
<hr>
<%= link_to 'Back to all restaurants', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Rating: <%= '⭐️' * (@restaurant.rating || 0) %></p>
<p>Address: <%= @restaurant.address %></p>
<hr>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete', restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
<%= link_to 'All restaurants', restaurants_path %>